apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
    name: dev-apps
resources:
    - ./podinfo/namespace.yaml
    - ./podinfo/deployment.yaml
    - ./podinfo/service.yaml
    - ./gitops-series/pod.yaml
    - ./gitops-series/namespace.yaml